version: '3.1'
services:
  postgres:
    container_name: ${POSTGRES_DOCKER_IMAGE_NAME}
    build: postgres/
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - INJECTED_METADATA=${INJECTED_METADATA}
      - SUPERSET_USERNAME=${SUPERSET_USERNAME}
      - SUPERSET_FIRSTNAME=${SUPERSET_FIRSTNAME}
      - SUPERSET_LASTNAME=${SUPERSET_LASTNAME}
      - SUPERSET_EMAIL=${SUPERSET_EMAIL}
      - SUPERSET_PASSWORD=${SUPERSET_PASSWORD}
      - DATABASE_DIALECT=${DATABASE_DIALECT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SUPERSET_DB=${SUPERSET_DB}
      - POSTGRES_DB=${POSTGRES_DB}
      - SLEEP_TIME=${SLEEP_TIME}
    volumes:
      - ./postgres/ddl:/docker-entrypoint-initdb.d/
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - general
  
  superset:
    container_name: ${SUPERSET_DOCKER_IMAGE_NAME}
    build: superset/
    restart: on-failure
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    networks:
      - general
    links: 
      - postgres
    environment:
      - INJECTED_METADATA=${INJECTED_METADATA}
      - SUPERSET_USERNAME=${SUPERSET_USERNAME}
      - SUPERSET_FIRSTNAME=${SUPERSET_FIRSTNAME}
      - SUPERSET_LASTNAME=${SUPERSET_LASTNAME}
      - SUPERSET_EMAIL=${SUPERSET_EMAIL}
      - SUPERSET_PASSWORD=${SUPERSET_PASSWORD}
      - DATABASE_DIALECT=${DATABASE_DIALECT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SUPERSET_DB=${SUPERSET_DB}
      - POSTGRES_DB=${POSTGRES_DB}
      - SLEEP_TIME=${SLEEP_TIME}

  superset_init:
    build: superset/
    restart: on-failure
    depends_on:
      - superset
    networks:
      - general
    links:
      - postgres
    command: >
      superset-init --username ${SUPERSET_USERNAME} --firstname ${SUPERSET_FIRSTNAME} \
      --lastname ${SUPERSET_LASTNAME} \
      --email ${SUPERSET_EMAIL} \
      --password ${SUPERSET_PASSWORD}
    environment:
      - INJECTED_METADATA=${INJECTED_METADATA}
      - SUPERSET_USERNAME=${SUPERSET_USERNAME}
      - SUPERSET_FIRSTNAME=${SUPERSET_FIRSTNAME}
      - SUPERSET_LASTNAME=${SUPERSET_LASTNAME}
      - SUPERSET_EMAIL=${SUPERSET_EMAIL}
      - SUPERSET_PASSWORD=${SUPERSET_PASSWORD}
      - DATABASE_DIALECT=${DATABASE_DIALECT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SUPERSET_DB=${SUPERSET_DB}
      - POSTGRES_DB=${POSTGRES_DB}
      - SLEEP_TIME=${SLEEP_TIME}

  postgres_metadata_load:
    image: docker
    privileged: true
    restart: on-failure
    depends_on:
      - superset_init
    networks:
      - general
    links:
      - postgres
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./postgres/dml/init_superset.sql:/postgres/init_superset.sql
      - ./postgres/ddl/load_superset_metadata.sh:/postgres/load_superset_metadata.sh
    environment:
      - INJECTED_METADATA=${INJECTED_METADATA}
      - SUPERSET_USERNAME=${SUPERSET_USERNAME}
      - SUPERSET_FIRSTNAME=${SUPERSET_FIRSTNAME}
      - SUPERSET_LASTNAME=${SUPERSET_LASTNAME}
      - SUPERSET_EMAIL=${SUPERSET_EMAIL}
      - SUPERSET_PASSWORD=${SUPERSET_PASSWORD}
      - DATABASE_DIALECT=${DATABASE_DIALECT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SUPERSET_DB=${SUPERSET_DB}
      - POSTGRES_DB=${POSTGRES_DB}
      - SLEEP_TIME=${SLEEP_TIME}
    command: docker cp postgres/init_superset.sql ${POSTGRES_DOCKER_IMAGE_NAME}:/tmp/init_superset.sql
    depends_on:
      - superset_init

  postgres_metadata_insertion:
    image: docker
    privileged: true
    restart: on-failure
    depends_on:
      - postgres_metadata_load
    networks:
      - general
    links:
      - postgres
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./postgres/ddl/load_superset_metadata.sh:/docker-entrypoint-initdb.d/load_superset_metadata.sh
    environment:
      - INJECTED_METADATA=${INJECTED_METADATA}
      - SUPERSET_USERNAME=${SUPERSET_USERNAME}
      - SUPERSET_FIRSTNAME=${SUPERSET_FIRSTNAME}
      - SUPERSET_LASTNAME=${SUPERSET_LASTNAME}
      - SUPERSET_EMAIL=${SUPERSET_EMAIL}
      - SUPERSET_PASSWORD=${SUPERSET_PASSWORD}
      - DATABASE_DIALECT=${DATABASE_DIALECT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SUPERSET_DB=${SUPERSET_DB}
      - POSTGRES_DB=${POSTGRES_DB}
      - SLEEP_TIME=${SLEEP_TIME}
    command: docker exec -u ${POSTGRES_USER} ${POSTGRES_DOCKER_IMAGE_NAME} sh /docker-entrypoint-initdb.d/load_superset_metadata.sh
    depends_on:
      - postgres_metadata_load
  spark:
      build: python/
      restart: on-failure
      ports:
        - "80:80"
        - "4040:4040"
      networks:
        - general
      links:
        - postgres
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      environment:
        - MODEL_PATH=${MODEL_PATH}
        - USED_JAR_PATH=${USED_JAR_PATH}
        - SPARK_MASTER_NAME=${SPARK_MASTER_NAME}
        - SPARK_MASTER_PORT=${SPARK_MASTER_PORT}
        - SPARK_APPLICATION_PYTHON_LOCATION=${SPARK_APPLICATION_PYTHON_LOCATION}
        - SPARK_APPLICATION_ARGS=${SPARK_APPLICATION_ARGS}
      depends_on:
        - postgres_metadata_insertion
networks:
    general:
        driver: bridge