FROM alpine:3.9.4

# TODO 
#
# INSTALAR SPARK: https://www.apache.org/dyn/closer.lua/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz
# INSTALAR PYTHON
# INSTALAR JAVA 8
# INSTALAR REQUIREMENTS.TXT
# ONBUILD RUN virtualenv /env && /env/bin/pip install -r /requirements.txt
#
#
# RUN add-apt-repository ppa:openjdk-r/ppa
# RUN sudo apt-get update
# RUN apt-get install openjdk-8-jdk
# RUN sudo update-alternatives --config java
#
